version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"

  python:
    image: quay.io/cdis/indexd:feat_GPE-788
    platform: linux/amd64
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - postgres
    network_mode: "service:postgres"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      PGHOST: postgres
    command: >
      bash -c "
      source /venv/bin/activate &&
      poetry install &&
      bash tests/ci_commands_script.sh
      # poetry run pytest -vv --cov=indexd --cov=migrations/versions --cov-append --cov-report xml tests
      "
