"""
This file is auto-generated by Alembic. It was updated manually to:
- set `target_metadata` so that Alembic can read the Indexd model and
auto-generate migrations;
- load the Indexd configuration in order to set `sqlalchemy.url` to the
configured DB URL;
- lock the DB during migrations to ensure only 1 migration runs at a time.
"""

import os
import sys
import logging
from logging.config import fileConfig
import asyncio

from sqlalchemy import pool, text
from sqlalchemy.ext.asyncio import create_async_engine
from sqlalchemy.orm import declarative_base
from alembic import context

# this is the Alembic Config object, which provides
# access to the values within the .ini file in use.
config = context.config

# Interpret the config file for Python logging.
if config.config_file_name is not None:
    fileConfig(config.config_file_name)
logger = logging.getLogger("indexd.alembic")
logger.setLevel(logging.INFO)

Base = declarative_base()
target_metadata = Base.metadata

# Inject the environment path so Alembic finds local_settings.py inside Docker
if "INDEXD_SETTINGS" in os.environ:
    sys.path.append(os.environ["INDEXD_SETTINGS"])

try:
    from local_settings import settings
except ImportError as e:
    logger.info("Can't import local_settings, import from default")
    from indexd.default_settings import settings

# Leave the URL untouched - Alembic will use asyncpg natively now!
conn_url = str(settings["config"]["INDEX"]["driver"].engine.url)
config.set_main_option("sqlalchemy.url", conn_url)


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    This configures the context with just a URL and not an Engine.
    Calls to context.execute() here emit the given string to the script output.
    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection) -> None:
    """
    The synchronous part of the online migration process.
    This is executed via `run_sync` by the async engine.
    """
    context.configure(connection=connection, target_metadata=target_metadata)

    with context.begin_transaction():
        if connection.dialect.name == "postgresql":
            logger.info(
                "Locking database to ensure only 1 process can run migrations at a time"
            )
            # Wrap the raw SQL in text() for SQLAlchemy 2.0 compatibility
            connection.execute(
                text(
                    f"SELECT pg_advisory_xact_lock({settings['config'].get('DB_MIGRATION_POSTGRES_LOCK_KEY', 100)});"
                )
            )
        else:
            logger.info(
                "Not running on Postgres: not locking database before migrating"
            )

        context.run_migrations()

    if connection.dialect.name == "postgresql":
        # The lock is released when the transaction ends.
        logger.info("Releasing database lock")


async def run_async_migrations() -> None:
    """
    Create an AsyncEngine, connect, and run the synchronous migration function.
    """
    connectable = create_async_engine(
        config.get_main_option("sqlalchemy.url"),
        poolclass=pool.NullPool,
    )
    try:
        async with connectable.connect() as connection:
            await connection.run_sync(do_run_migrations)
    except Exception as e:
        print(e)

    await connectable.dispose()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode."""
    # Since app.py calls this in a separate thread via `asyncio.to_thread`,
    # we can safely spin up a new event loop here.
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
