#!/bin/bash
# these are set in supervisor's environment by upstart (presumably),
# but we don't want them so we unset them here
unset http_proxy
unset https_proxy

PYTHON=/usr/bin/python
SCRIPT=/indexd/bin/migrate_index.py
exec $PYTHON $SCRIPT
